const RestroItems = [
  {
    id: 1,
    name: "John Doe",
    phoneNumber: "555-1234",
    email: "john.doe@example.com",
    dish: "Spaghetti Bolognese",
    restaurant: "Italian Delight",
  },
  {
    id: 2,
    name: "Jane Smith",
    phoneNumber: "555-5678",
    email: "jane.smith@example.com",
    dish: "Chicken Tandoori",
    restaurant: "Spice Paradise",
  },
  {
    id: 3,
    name: "Alex Johnson",
    phoneNumber: "555-9876",
    email: "alex.johnson@example.com",
    dish: "Sushi Platter",
    restaurant: "Tokyo Delights",
  },
  {
    id: 4,
    name: "Emily Davis",
    phoneNumber: "555-4321",
    email: "emily.davis@example.com",
    dish: "BBQ Ribs",
    restaurant: "Smokehouse Grill",
  },
  {
    id: 5,
    name: "Michael Brown",
    phoneNumber: "555-8765",
    email: "michael.brown@example.com",
    dish: "Margarita Pizza",
    restaurant: "Pizzeria Italia",
  },
  {
    id: 6,
    name: "Olivia White",
    phoneNumber: "555-2345",
    email: "olivia.white@example.com",
    dish: "Pad Thai",
    restaurant: "Thai Fusion",
  },
  {
    id: 7,
    name: "Daniel Miller",
    phoneNumber: "555-6543",
    email: "daniel.miller@example.com",
    dish: "Falafel Wrap",
    restaurant: "Mediterranean Bites",
  },
  {
    id: 8,
    name: "Sophia Taylor",
    phoneNumber: "555-8765",
    email: "sophia.taylor@example.com",
    dish: "Sashimi Platter",
    restaurant: "Sakura Sushi",
  },
  {
    id: 9,
    name: "William Wilson",
    phoneNumber: "555-3456",
    email: "william.wilson@example.com",
    dish: "Steak au Poivre",
    restaurant: "Bistro du Chef",
  },
  {
    id: 10,
    name: "Ella Anderson",
    phoneNumber: "555-7890",
    email: "ella.anderson@example.com",
    dish: "Vegetarian Lasagna",
    restaurant: "Green Cuisine",
  },
  {
    id: 11,
    name: "Rajesh Kumar",
    phoneNumber: "555-1111",
    email: "rajesh.kumar@example.com",
    dish: "Butter Chicken",
    restaurant: "Spice Kingdom",
  },
  {
    id: 12,
    name: "Priya Sharma",
    phoneNumber: "555-2222",
    email: "priya.sharma@example.com",
    dish: "Paneer Tikka Masala",
    restaurant: "Tandoori Delight",
  },
  {
    id: 13,
    name: "Amit Patel",
    phoneNumber: "555-3333",
    email: "amit.patel@example.com",
    dish: "Dosa with Sambar",
    restaurant: "South Indian Flavors",
  },
  {
    id: 14,
    name: "Neha Singh",
    phoneNumber: "555-4444",
    email: "neha.singh@example.com",
    dish: "Rogan Josh",
    restaurant: "Curry House",
  },
  {
    id: 15,
    name: "Sanjay Verma",
    phoneNumber: "555-5555",
    email: "sanjay.verma@example.com",
    dish: "Biryani",
    restaurant: "Royal Biryani Palace",
  },
  {
    id: 16,
    name: "Anita Das",
    phoneNumber: "555-6666",
    email: "anita.das@example.com",
    dish: "Chole Bhature",
    restaurant: "Punjabi Dhaba",
  },
  {
    id: 17,
    name: "Rahul Kapoor",
    phoneNumber: "555-7777",
    email: "rahul.kapoor@example.com",
    dish: "Masala Dosa",
    restaurant: "Udupi Sagar",
  },
  {
    id: 18,
    name: "Sonia Reddy",
    phoneNumber: "555-8888",
    email: "sonia.reddy@example.com",
    dish: "Palak Paneer",
    restaurant: "Green Spice",
  },
  {
    id: 19,
    name: "Vikram Desai",
    phoneNumber: "555-9999",
    email: "vikram.desai@example.com",
    dish: "Samosa Chaat",
    restaurant: "Chatkara Street Food",
  },
  {
    id: 20,
    name: "Meera Joshi",
    phoneNumber: "555-0000",
    email: "meera.joshi@example.com",
    dish: "Mango Lassi",
    restaurant: "Mango Paradise",
  },
];

export { RestroItems };
